-- Inserting from ProjectRoles.csv
INSERT IGNORE INTO ProjectRoles(Name) VALUES
  ("Project Manager"),
  ("Program Manager"),
  ("Scrum Master"),
  ("Product Owner"),
  ("Project Coordinator"),
  ("Software Developer"),
  ("Frontend Developer"),
  ("Backend Developer"),
  ("Mobile Developer"),
  ("Embedded Systems Developer"),
  ("DevOps Engineer"),
  ("Site Reliability Engineer"),
  ("Quality Assurance Engineer"),
  ("Test Automation Engineer"),
  ("Database Administrator"),
  ("Security Engineer"),
  ("Systems Architect"),
  ("UI Designer"),
  ("UX Designer"),
  ("Interaction Designer"),
  ("Visual Designer"),
  ("User Researcher"),
  ("Information Architect"),
  ("Product Manager"),
  ("Business Analyst"),
  ("Product Marketing Manager"),
  ("Product Designer"),
  ("Growth Manager"),
  ("Sales Manager"),
  ("Account Executive"),
  ("Sales Development Representative"),
  ("Customer Success Manager"),
  ("Marketing Manager"),
  ("Content Marketing Specialist"),
  ("Social Media Manager"),
  ("SEO/SEM Specialist"),
  ("Email Marketing Specialist"),
  ("Partnerships Manager"),
  ("Public Relations Manager"),
  ("Customer Support Manager"),
  ("Support Specialist"),
  ("Onboarding Specialist"),
  ("Knowledge Base Manager"),
  ("Technical Support Engineer"),
  ("Performance Tester"),
  ("Human Resources Manager"),
  ("Talent Acquisition Specialist"),
  ("Training and Development Specialist"),
  ("Compensation and Benefits Specialist"),
  ("Employee Relations Manager"),
  ("Finance Manager"),
  ("Financial Analyst"),
  ("Accountant"),
  ("Controller"),
  ("Tax Manager"),
  ("Corporate Counsel"),
  ("Intellectual Property Lawyer"),
  ("Contract Manager"),
  ("Compliance Officer"),
  ("Information Technology Manager"),
  ("Systems Administrator"),
  ("Network Engineer"),
  ("IT Support Specialist"),
  ("Help Desk Technician"),
  ("Business Development Manager"),
  ("Strategic Partnerships Manager"),
  ("Channel Partner Manager"),
  ("Research/Development Manager"),
  ("Research Scientist"),
  ("Data Scientist"),
  ("Machine Learning Engineer"),
  ("Operations Manager"),
  ("Business Operations Analyst"),
  ("Procurement Manager");
-- Inserting from Positions.csv
INSERT IGNORE INTO Positions(Name, MinimumSalary, MaximumSalary) VALUES
  ("Chief Technology Officer", "180000", "300000"),
  ("Vice President of Engineering", "150000", "250000"),
  ("Engineering Manager", "110000", "170000"),
  ("Product Owner", "90000", "150000"),
  ("Software Developer", "70000", "120000"),
  ("Senior Software Developer", "90000", "150000"),
  ("Frontend Developer", "65000", "110000"),
  ("Backend Developer", "75000", "125000"),
  ("System Architect", "100000", "160000"),
  ("DevOps Engineer", "85000", "140000"),
  ("QA Engineer", "60000", "100000"),
  ("Senior QA Engineer", "80000", "130000"),
  ("Security Engineer", "90000", "150000"),
  ("Software Architect", "120000", "180000"),
  ("UI/UX Designer", "70000", "110000"),
  ("UX Researcher", "65000", "105000"),
  ("Product Manager", "100000", "160000"),
  ("Business Analyst", "70000", "100000"),
  ("Product Designer", "75000", "120000"),
  ("Vice President of Sales", "150000", "250000"),
  ("Sales Manager", "85000", "140000"),
  ("Sales Engineer", "80000", "130000"),
  ("Account Executive", "80000", "130000"),
  ("Customer Success Manager", "75000", "125000"),
  ("Chief Marketing Officer", "140000", "220000"),
  ("Content Marketing Specialist", "55000", "95000"),
  ("Digital Marketing Manager", "70000", "110000"),
  ("Customer Support Manager", "75000", "120000"),
  ("Customer Support Representative", "40000", "70000"),
  ("Technical Support Engineer", "55000", "90000"),
  ("Human Resources Manager", "75000", "125000"),
  ("Talent Acquisition Specialist", "50000", "90000"),
  ("Finance Manager", "95000", "150000"),
  ("Chief Financial Officer", "150000", "250000"),
  ("Corporate Counsel", "110000", "200000"),
  ("Compliance Officer", "90000", "140000"),
  ("Systems Administrator", "65000", "100000"),
  ("Network Engineer", "75000", "115000"),
  ("Cloud Engineer", "85000", "140000"),
  ("Cloud Architect", "110000", "170000"),
  ("Business Development Manager", "85000", "130000"),
  ("Data Scientist", "90000", "150000"),
  ("Data Analyst", "60000", "100000"),
  ("Machine Learning Engineer", "100000", "160000"),
  ("Operations Manager", "80000", "130000");
-- Inserting from EmploymentTypes.csv
INSERT IGNORE INTO EmploymentTypes(Name) VALUES
  ("Full-Time"),
  ("Part-Time"),
  ("Temporary"),
  ("Contractor"),
  ("Apprentice"),
  ("Intern"),
  ("Seasonal"),
  ("Consultant");
-- Inserting from States.csv
INSERT IGNORE INTO States(Name) VALUES
  ("AL"),
  ("AK"),
  ("AZ"),
  ("AR"),
  ("CA"),
  ("CO"),
  ("CT"),
  ("DE"),
  ("FL"),
  ("GA"),
  ("HI"),
  ("ID"),
  ("IL"),
  ("IN"),
  ("IA"),
  ("KS"),
  ("KY"),
  ("LA"),
  ("ME"),
  ("MD"),
  ("MA"),
  ("MI"),
  ("MN"),
  ("MS"),
  ("MO"),
  ("MT"),
  ("NE"),
  ("NV"),
  ("NH"),
  ("NJ"),
  ("NM"),
  ("NY"),
  ("NC"),
  ("ND"),
  ("OH"),
  ("OK"),
  ("OR"),
  ("PA"),
  ("RI"),
  ("SC"),
  ("SD"),
  ("TN"),
  ("TX"),
  ("UT"),
  ("VT"),
  ("VA"),
  ("WA"),
  ("WV"),
  ("WI"),
  ("WY"),
  ("DC"),
  ("GU"),
  ("MH"),
  ("MP"),
  ("PR"),
  ("VI");
-- Inserting from Degrees.csv
INSERT IGNORE INTO Degrees(Name) VALUES
  ("Diploma"),
  ("Associate"),
  ("Bachelor"),
  ("Master"),
  ("Doctoral");
-- Inserting from Departments.csv
INSERT IGNORE INTO Departments(Name) VALUES
  ("Software Development"),
  ("Quality Assurance"),
  ("UI/UX Design"),
  ("Sales and Marketing"),
  ("Customer Success"),
  ("Customer Support"),
  ("Human Resources"),
  ("Operations"),
  ("Finance"),
  ("Legal"),
  ("Information Technology"),
  ("Business Development"),
  ("Security and Compliance"),
  ("Research and Development"),
  ("Data Science and Analytics"),
  ("Strategy and Corporate Development"),
  ("Public Relations and Communications"),
  ("Cloud Operations"),
  ("Community Management"),
  ("Knowledge Management"),
  ("Internal Communications");
-- Inserting from Benefits.csv
INSERT IGNORE INTO Benefits(Name) VALUES
  ("Health Insurance"),
  ("Parental Leave"),
  ("Retirement Benefits"),
  ("Stock Options/Equity"),
  ("Disability Insurance"),
  ("Life Insurance"),
  ("Commuter Benefits"),
  ("Tuition Reimbursement"),
  ("Vacation Leave");
